services:
  loanhub.bank.api:
    image: ${DOCKER_REGISTRY-}loanhubbankapi
    build:
      context: .
      dockerfile: src/LoanHub.Bank.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=LoanHubBank;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False
    depends_on:
      - sqlserver
    ports:
      - "9999:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
